# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PisoPlazaDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=pisoplaza_user
spring.datasource.password=PisoPlaza2026
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT
app.jwt.secret=clave-secreta-muy-larga-para-mercado-jalapa-2024-segura
app.jwt.expiration=86400000

# Puerto
server.port=8080